### ISSUE TITLE
DropDownList not working after Chrome restart, page refresh or new snapshot

### ISSUE THREAD

**Issue by bastyanix** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#105]
Hi,

I have a problem that whenever I restart Chrome (after a computer restart for example) or after the page refreshes or after I make a new snapshot or even after I export the code, delete the canvas and reimport the code - the DropDownList(s) that I currently have in the dialog in the preview window are not working (meaning they do not expand to the bottom when clicked). The only way that I found to make them work (again) is to manually duplicate (with alt+drag) each DropDownList and the new duplicated one will work normally (after that you delete the old one of course).

Where is the problem? Anyone having this issue?

P.S.: congrats Joonas!! This is a great and very useful app!!

**Comment by joonaspaakko** [comment]
@bastyanix, it's fixed now.

This took a hot second to figure out since there were no errors or missing files or anything... It turns out I was loading in Javascript and CSS on page load for CEP panel export in a way that it was accidentally executing the Javascript and overwriting certain event listeners, which is why newly created items didnt have the issue. The Javascript in question was only able to attach the event listeners to elements that existed on page load.

**Comment by bastyanix** [comment]
Hi Joonas,

that's great!! I can confirm that everything is working great now!
Thank you!
