### ISSUE TITLE
'statictext' renders differently in ScriptUI

### ISSUE THREAD

**Issue by sergey-kritskiy** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#12]
Hi Joonas, I'm having an issue with statictext, I'm not sure what's happening exactly, but statictext is being cut by it's group. I realise it's a ScriptUI issue but I wonder if it's possible to fix somehow.
Here's a JSON of a panel I built: 
`{"activeId":0,"items":{"item-0":{"id":0,"type":"Dialog","parentId":false,"style":{"text":"Dialog","preferredSize":[600,400],"margins":16,"orientation":"column","spacing":10,"alignChildren":["center","top"]}},"item-1":{"id":1,"type":"Group","parentId":0,"style":{"preferredSize":[400,0],"margins":0,"orientation":"row","spacing":10,"alignChildren":["center","center"],"alignment":"center"}},"item-2":{"id":2,"type":"Group","parentId":0,"style":{"preferredSize":[0,0],"margins":0,"orientation":"row","spacing":10,"alignChildren":["left","center"],"alignment":null}},"item-3":{"id":3,"type":"Button","parentId":2,"style":{"text":"Button","justify":"center","preferredSize":[0,0],"alignment":null}},"item-4":{"id":4,"type":"Button","parentId":2,"style":{"text":"Button","justify":"center","preferredSize":[0,0],"alignment":null}},"item-5":{"id":5,"type":"Button","parentId":2,"style":{"text":"Button","justify":"center","preferredSize":[0,0],"alignment":null}},"item-6":{"id":6,"type":"StaticText","parentId":1,"style":{"text":"Warning! Photoshop Scripts folder is read only: duplicating, renaming and deleting is disabled. Restart Photoshop as Administrator to re-enable those functions.","justify":"left","preferredSize":[399,0],"alignment":"center"}}},"order":[0,1,6,2,3,4,5]}`

expected result:
http://prntscr.com/lrzhr6

actual result: 
http://prntscr.com/lrzhxh

**Comment by joonaspaakko** [comment]
Hi. Didn't mean to close the question. I was just kinda careless with the good ole mouse there.

Yes. This is a bit of an oversight on my part. I used to have a restriction where items in the dialog preview would never be smaller than the content, no matter what user inputs. The input width would be defined in the export, but ScriptUI would essentially ignore it because it's a "preferred" size and statictext doesn't do softwraps. Very recently I made a change to it so that it only applies to parent items. Honestly, I forgot why I implemented that in the first place. Now you have reminded me :) 

**I need to rethink how to solve that.**

The solution for your _right now_ might be to add manual line breaks instead. Although that looks to have an issue as well. It looks like ScriptUI leaves a gap between the text and the buttons when the width is defined ([at least in AI CC 2019](https://user-images.githubusercontent.com/1164476/49653395-75bbef80-fa3d-11e8-9241-7af7ad40ca01.png)):


```json
{"activeId":6,"items":{"item-0":{"id":0,"type":"Dialog","parentId":false,"style":{"text":"Dialog","preferredSize":[600,400],"margins":16,"orientation":"column","spacing":10,"alignChildren":["center","top"]}},"item-1":{"id":1,"type":"Group","parentId":0,"style":{"preferredSize":[400,0],"margins":0,"orientation":"row","spacing":10,"alignChildren":["center","center"],"alignment":"center"}},"item-2":{"id":2,"type":"Group","parentId":0,"style":{"preferredSize":[0,0],"margins":0,"orientation":"row","spacing":10,"alignChildren":["left","center"],"alignment":null}},"item-3":{"id":3,"type":"Button","parentId":2,"style":{"text":"Button","justify":"center","preferredSize":[0,0],"alignment":null}},"item-4":{"id":4,"type":"Button","parentId":2,"style":{"text":"Button","justify":"center","preferredSize":[0,0],"alignment":null}},"item-5":{"id":5,"type":"Button","parentId":2,"style":{"text":"Button","justify":"center","preferredSize":[0,0],"alignment":null}},"item-6":{"id":6,"type":"StaticText","parentId":1,"style":{"text":"Warning! Photoshop Scripts folder is read only: duplicating,\nrenaming and deleting is disabled. Restart Photoshop as \nAdministrator to re-enable those functions.","justify":"left","preferredSize":[399,0],"alignment":"center"}}},"order":[0,1,6,2,3,4,5]}
```

**Comment by sergey-kritskiy** [comment]
With multiline I think it's a different issue (https://forums.adobe.com/thread/1260079), they're using `characters` to determine width of multiline statictexts :/

**Comment by joonaspaakko** [comment]
I was thinking that gap issue might happen because the size is defined after the item is created. ScriptUI can be picky about that. I'll have to look into that as well.

**Comment by joonaspaakko** [comment]
@sergey-kritskiy, this should be resolved for now... Although I have to elaborate a bit.

So this issue brought up the possibility that yes, I could support soft wrapping text... so I was like "Let's try that". What a naive man I was back then. A big factor with this not going like in the movies was that I could not for the life of me figure out a way to set multiline text reliably without setting a static width and height. The solutions in the post in Adobe forums you linked to didn't work reliably (mainly Photoshop) and I couldn't come up with anything else.

Setting width and height is fine if a vacuum, but in this case, it means that the text in this builder's dialog preview needs to be pixel perfect with scriptui. Because if I define height as 100 and the text takes up 6 rows in the dialog preview and 7 rows in the scriptui, 1 row is going to be cut off.

**As of now, soft wrapping text is in probation.** If I get complaints about this not working out, I'll just remove it and make it so that both text items `StaticText` and `EditText` can only be as small as their contents.

**Comment by joonaspaakko** [comment]
@sergey-kritskiy, I couldn't let this go. I got rid of the text flow issues in `StaticText` by dividing it into multiple elements on export. **So now it should be fixed for good.**

EditText has to try and hang in there as obviously the same solution won't work with that.
