### ISSUE TITLE
Request: Ability to change variable names in exported code.

### ISSUE THREAD

**Issue by jedSavage** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#24]
Ability to name the variables in the exported code. 

e.g.:
`var group2 = dialog.add("group"); 
    group2.orientation = "row"; 
    group2.alignChildren = ["left","center"]; 
    group2.spacing = 10; 
    group2.margins = 0; `

Instead of "group2", I could, using the interface to name it something else - like "optioanlParams".

**Comment by joonaspaakko** [comment]
@jedSavage, I've now added custom variables. In case you're interested... I also added snapshots (the collapsed panel on the very right). 

**Few more things about custom variables:** 

- For now I've made it so custom variable names are converted to `camelCase` on export. 
    - For example:
        - `MyItem` becomes: `var myItem =`
        - `MYITEM` becomes: `var mYITEM =`
        - `my item` becomes: `var myItem =`
        - `my_item` becomes: `var my_item =`
        - `my_Item` becomes: `var my_Item =`
- Duplicate variable names get number increments just like variable names normally do.

**Comment by jedSavage** [comment]
This is awesome, thank you!  You might want to add some variable name validation eventually. As-is, you can export variable names which are not valid in JS, e.g. "123var", "A-3", etc...

I'd also prefer to be able to use whatever naming style I want rather than having camelCase enforced.

Good job on this!

**Comment by joonaspaakko** [comment]
@jedSavage, I don't think I'll ever do a bulletproof validation since some level of understanding is required anyways, but I do have a fix coming that makes the camelcase conversion more reliable and preserve the uppercase first character. 

There is also another fix that is coming up. The exported code has `dialog.show();` at the very end, which I forgot is a simple string and as such, it stays the same no matter what the custom variable is.

**Comment by jedSavage** [comment]
If you change your mind, you should be able to do a fairly simple validation using regex, e.g. "^[a-zA-Z$_][a-zA-Z0-9$_]*$" should match all possible valid variable names.
