### ISSUE TITLE
Feature Request: Right click on a control to copy object hierarchy...

### ISSUE THREAD

**Issue by jedSavage** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#31]
When adding events to controls, it would be nice to be able to right click on a control and have a context menu appear where I could copy the object hierarchy into the clipboard.

![screen shot 03-08-19 at 09 30 am](https://user-images.githubusercontent.com/14342067/54041495-17f68b00-4185-11e9-97ab-3f81342db918.PNG)

**Comment by joonaspaakko** [comment]
My first instict is that this is unnecessary, because you could simply hook into that variable like this:

```Javascript
$.writeln( staticText2.text );
```
_...or give it a custom variable and use that._

You might want to put the dialog inside a function, in which case it would become slightly harder to access the values as you can't directly access those variables from outside, but I would claim it's easy enough to get around it...

## The long explanation: 

Thing is... the way the code is exported right now, it doesn't actually quite support traversing the object the way you suggest, since the items are nameless. The items are just given variable hooks outside of the object structure. Meaning that every single time the dialog export has a line that starts with `var ...` you can grab onto that variable name instead of having to go through every single parent item.

The code structure was one of those things I put a lot of time thinking about when I first created the export feature. As an example... One of the options was exporting the whole object as a string(#23). I ended up going with what I thought would be sort of the best of all worlds which I'm sure some might disagree with.

### As an example of why this wouldn't work right now:

_Check the last few lines of the first code block below_

```Javascript
// DIALOG
// ======
var dialog = new Window("dialog"); 

// GROUP6
// ======
var group6 = dialog.add("group"); 
    group6.orientation = "column"; 
    group6.alignChildren = ["fill","top"]; 
    group6.spacing = 10; 
    group6.margins = 0; 

var button1 = group6.add("button"); 
    button1.text = "OK"; 
    button1.justify = "center"; 

var button2 = group6.add("button"); 
    button2.text = "Cancel"; 
    button2.justify = "center"; 

// This doesn't return anything because 'group6' and 'button1' don't exist.
$.writeln( dialog.group6.button1.text ); 
```

To make fetch the text in a similar similar fashion, you'd actually have to do something like this:

```Javascript
$.writeln( dialog.children[0].children[0].text );
```

**The way I imagined this would be done was this:**

I would claim there is no need for this feature you are suggesting, because it's just a simple variable and not like a full sentence to access one item and its properties.  It just makes it so much cleaner in my opinion.

```Javascript
$.writeln( button1.text ); // or whatever custom variable you've given the button.
```

### One of the export formats I considered...

_...and swiftly discarded._

If we straight up just wanted to access items this way... This would be what that code would could like. I'm not a fan of this at all... In the worst case scenario you'll be writing a small novel trying to access an item that is nested deep within the dialog stucture. Your image example is also a good example of how cumbersome it would be.

```Javascript
// DIALOG
// ======
var dialog = new Window("dialog"); 

// GROUP6
// ======
dialog.group6 = dialog.add("group"); 
dialog.group6.orientation = "column"; 
dialog.group6.alignChildren = ["fill","top"]; 
dialog.group6.spacing = 10; 
dialog.group6.margins = 0; 

dialog.group6.button1 = dialog.group6.add("button"); 
dialog.group6.button1.text = "OK"; 
dialog.group6.button1.justify = "center"; 

dialog.group6.button2 = dialog.group6.add("button"); 
dialog.group6.button2.text = "Cancel"; 
dialog.group6.button2.justify = "center"; 

// This returns the text: OK
$.writeln( dialog.group6.button1.text );
```

### That said, I did also have this idea...

This is sort of a hybrid... You get both options, but still the exported code has the potential to become quite unwieldy. Especially if we would need to go like a dozen levels deeper.

```Javascript
// DIALOG
// ======
var dialog = new Window("dialog"); 

// GROUP6
// ======
dialog.group6 = dialog.add("group"); 
var group6 = dialog.group6;
    group6.orientation = "column"; 
    group6.alignChildren = ["fill","top"]; 
    group6.spacing = 10; 
    group6.margins = 0; 

dialog.group6.button1 = dialog.group6.add("button"); 
var button1 = dialog.group6.button1;
    button1.text = "OK"; 
    button1.justify = "center"; 

dialog.group6.button2 = dialog.group6.add("button"); 
var button2 = dialog.group6.button2;
    button2.text = "Cancel"; 
    button2.justify = "center"; 
		
// This returns the text: OK
$.writeln( dialog.group6.button1.text );
// This returns the text: OK
$.writeln( button1.text );
````

**Comment by joonaspaakko** [comment]
Oh yeah. The reason I've not close this yet is I'm thinking that if I ever add #23 this would suddenly start making a lot of sense. So at least for a while I'm keeping both open as a reminder.

- - - - - - 

Though I would rather add the context menu to the Structure Panel. Much simpler that way. Some items in the dialog preview would be pretty tough to click... `group` item for eaxample.

**Comment by joonaspaakko** [comment]
You can now copy item path to clipboard by right-clicking it in the structure panel. Related to #53.

> It works in the structure panel and to some degree in the dialog preview as well. 

![2019-08-25 22 44 28](https://user-images.githubusercontent.com/1164476/63654960-7a226700-c78a-11e9-8df6-00b128252548.gif)
