### ISSUE TITLE
Expand the tool to build "Palette" and "Window" along with the "Dialog" builder

### ISSUE THREAD

**Issue by jetrotal** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#50]
This is a powerfull tool that could create not only dialogs, but floating panels for after effects.

Here are the basic settings from a similar tool called "P9 scriptUI builder" for after effects.

![image](https://user-images.githubusercontent.com/45118493/58863429-376c5980-8689-11e9-9071-f80fc0786c17.png)
![image](https://user-images.githubusercontent.com/45118493/58863990-4e5f7b80-868a-11e9-8188-89d46123aa67.png)

This is how it builds the ScriptUI when "Workspace" is off:
`win=new Window("palette","new project",[0,0,500,500],{resizeable:true,borderless:true,independent:false,minimizeButton:false,maximizeButton:false,closeButton:false,});
win.center();
win.show();
`

And when "Workspace" is on:
`UI(this)
function UI(object){
var win = (object instanceof Panel) ? object : new Window("palette","new project",[0,0,500,500],{resizeable:true,borderless:true,independent:false,minimizeButton:false,maximizeButton:false,closeButton:false,});
}`

**Comment by joonaspaakko** [comment]
I don't see any issues in me adding that option. 

> It wouldn't be a huge deal to just replace the `new Window("dialog")` with `new Window("palette")` by hand, but if you're iterating on it the _dialog_ layout and you have to constantly manually type it in, I can see how that would be irritating.

### Implementation...?

1. It could be put in the properties panel when the "Dialog" item is active.
    - There are a few places where I would have to make sure to rename the "Dialog" to the window type.
    - I think I'll make the default variable name based on the window type. But I guess it could just as well be just a generic `var win` for all types.

2. Since they are there, I'll mention that I've not felt super compelled to add these window style options (close button, maximize button, etc...) but if you can convince me why they should be added, I can consider it.

3. The workspace option: Just thinking about it is making me **seriously reconsider** this issue #48, which I already committed to. This is a good example of why I was hesitant about that and any customization that is sort of different based on everyone's own preferences. In this case though... A function wrapper can easily be written once and then you can just copy&paste the dialog inside that all willy nilly. If I start supporting these things, It's going to end up with like 10 different function wrappers based on users own quirks and preferences.

**Comment by jetrotal** [comment]
Yeah, i keep editing it over and over, when i want to dock a scriptUI on a Panel Group, or test a responsive layout to a panel that i can be resized by the user.

1 - If the "Dialog" name is hard coded in many places, you could call them "Project".

-----------------------------------

2 - The "resizeable" helps who wants to make responsible layouts to their panels, like in the shapeLayer Toolbar Script:
![image](https://user-images.githubusercontent.com/45118493/58870837-51149d80-8697-11e9-9fb1-850ecc475294.png)
![image](https://user-images.githubusercontent.com/45118493/58870917-76091080-8697-11e9-8267-3c82609f4c49.png)


Some people create "help", "about me", or even "Image visualizer" panels too usign these options. 
The "borderless" option removes entirely the Title from the panel.

Another famous example that use these options, is the Quick Menu extension for After Effects. It has a keyboard mode only, so The only way to leave the Quick Menu panel, is to Hit Enter, or Hit Esc on keyboard.
![image](https://user-images.githubusercontent.com/45118493/58869923-8ae4a480-8695-11e9-94ef-60c353f250a5.png)



--------------------------------

3 - i don't understand the logic behind on this. so i can't give my opinion on it.

**Comment by joonaspaakko** [comment]
1. Window type can now be changed: 
![Screen Shot 2019-08-25 at 11 19 10 PM](https://user-images.githubusercontent.com/1164476/63655272-ce2f4a80-c78e-11e9-8e38-390713c855e7.png)

2. Creation properties have now been added ( https://github.com/joonaspaakko/ScriptUI-Dialog-Builder-Joonas/issues/51#issuecomment-524660400 ).

3. A function wrapper has also been added: https://github.com/joonaspaakko/ScriptUI-Dialog-Builder-Joonas/issues/48#issuecomment-524659760 — This is not exactly the same as the one you suggested, but I won't be adding more than one.
