### ISSUE TITLE
Feature Request: Add code which will pull Data from textfields, checkboxes an all other changeable items

### ISSUE THREAD

**Issue by AlexMuc2** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#63]
Hi Joonas,
if we have a complex dialog as in your sample it would be very useful to have a code block or at least a simple list with all used 'var xxx'. It would save a Lot of Typung or copy/paste :-)

Michael

**Comment by joonaspaakko** [comment]
Hi Alex, got any ideas how that should happen?

Right now there is a way to copy various path types per a single item: https://github.com/joonaspaakko/ScriptUI-Dialog-Builder-Joonas/issues/31#issuecomment-524658433

**Is that ↑ good enough on its own?** See my first thought was that to me it would make more sense to cherry pick the items I want to edit, rather than copy & paste every single item with a custom name every single time. Downsides to both approaches, I guess.

- - - - 

### Some thoughts...

What if these context menu items were changed to `copy for all custom named items(or whatever)` when the modifier `alt` is pressed down. This seems pretty efficient to me, but the not so great part about this idea is that it would add the already hard to find context menu another hidden feature that is pretty much impossible to find on your own. But simply adding in 3 other copy commands adds too much clutter, I think...

Another thought I had was to add an export option that would list all items with custom names at the very bottom of the code. But then the question is which output format to use: "findElement", "variable name" or "item path"... Which, off the top of my head would probably require me to add an export option for each. Not really an issue, just thinking out loud.

**Comment by AlexMuc2** [comment]
Hi Jonas,
the "copy Path" is a good Start for one or two items. But if you have more than five than it's becoming work... and as you can See, the full path isn't real needed.
I've attached my current "sample" where I' trying to figure out how everything works. Because I'm an applescript guy it took some time to put things in javascript together.
Best Way for newbies like me would be a "ready to run" source but it would be OK if you can simply the Part in the return block. Having lots of fielddata to extract with this part would take us much faster to a running source :-)
so take a Look to my samplefile and than think about it what makes sense and whats not. Because I'm new to this stuff I like it easy ;->

The part after `var shownDialog = createDialogWindow();` would be an only nice to have.
[Muster 2.jsx.zip](https://github.com/joonaspaakko/ScriptUI-Dialog-Builder-Joonas/files/3588074/Muster.2.jsx.zip)

**Comment by joonaspaakko** [comment]
Alright, looking at the file I think what you want goes a tad further than what I'd be willing to do for now. I think it's a little bit too specific for my tastes. 

**Thoughts:**

- Who am I to assume people who want this list of items would also want to get the `value` or `text` or whatever.
- Just because an item has a `value` doesn't mean you need to necessarily fetch it. 
- If I do add some properties, such as `text` or `value`, why not then also add every single property it's given?
- I think I would be ready to add this feature, but I wouldn't include any properties. I would add it as a sort of a reference list. This way you wouldn't need to jump between SDB and your code editor of choice to lookup which item is which. _Maybe..._
- My fear is that I personally would look at that list and go: `"Alright so what is this item that I named "jimmyJohn02"` and then I would still have to go hunt it down.

**Either way, this is what I'd be ready to implement right now:**

A new export option that "prints" an `Item Reference List` at the bottom. You could choose any of the context menu copy formats: `variable name`, `findElement`, `item path`. **Check the very bottom of this code block below ↓**

Would this be acceptable for you or do you think you'd still want more from it?

> I put 3 comment blocks at the bottom as an example, but as I suggested, only one of these blocks would be exported based on the export option.

```Javascript
/*
Code for Import https://scriptui.joonas.me — (Triple click to select): 
{"activeId":7,"items":{"item-0":{"id":0,"type":"Dialog","parentId":false,"style":{"enabled":true,"varName":null,"windowType":"Dialog","creationProps":{"su1PanelCoordinates":false,"maximizeButton":false,"minimizeButton":false,"independent":false,"closeButton":true,"borderless":false,"resizeable":false},"text":"Dialog","preferredSize":[0,0],"margins":16,"orientation":"row","spacing":10,"alignChildren":["center","top"]}},"item-1":{"id":1,"type":"Panel","parentId":0,"style":{"enabled":true,"varName":null,"creationProps":{"borderStyle":"etched","su1PanelCoordinates":false},"text":"Panel","preferredSize":[0,0],"margins":10,"orientation":"column","spacing":10,"alignChildren":["left","top"],"alignment":null}},"item-5":{"id":5,"type":"Group","parentId":0,"style":{"enabled":true,"varName":null,"preferredSize":[0,0],"margins":0,"orientation":"column","spacing":10,"alignChildren":["fill","center"],"alignment":null}},"item-6":{"id":6,"type":"Button","parentId":5,"style":{"enabled":true,"varName":"ok","text":"Ok","justify":"center","preferredSize":[0,0],"alignment":null,"helpTip":null}},"item-7":{"id":7,"type":"Button","parentId":5,"style":{"enabled":true,"varName":"cancel","text":"Cancel","justify":"center","preferredSize":[0,0],"alignment":null,"helpTip":null}},"item-8":{"id":8,"type":"EditText","parentId":1,"style":{"enabled":true,"varName":"textInput","creationProps":{"noecho":false,"readonly":false,"multiline":false,"scrollable":false,"borderless":false,"enterKeySignalsOnChange":false},"softWrap":false,"text":"EditText","justify":"left","preferredSize":[157,0],"alignment":null,"helpTip":null}}},"order":[0,1,8,5,6,7],"settings":{"importJSON":true,"indentSize":false,"cepExport":false,"includeCSSJS":true,"showDialog":true,"functionWrapper":false,"compactCode":false}}
*/ 

// DIALOG
// ======
var dialog = new Window("dialog"); 
    dialog.text = "Dialog"; 
    dialog.orientation = "row"; 
    dialog.alignChildren = ["center","top"]; 
    dialog.spacing = 10; 
    dialog.margins = 16; 

// PANEL1
// ======
var panel1 = dialog.add("panel", undefined, undefined, {name: "panel1"}); 
    panel1.text = "Panel"; 
    panel1.orientation = "column"; 
    panel1.alignChildren = ["left","top"]; 
    panel1.spacing = 10; 
    panel1.margins = 10; 

var textInput = panel1.add('edittext {properties: {name: "textInput"}}'); 
    textInput.text = "EditText"; 
    textInput.preferredSize.width = 157; 

// GROUP1
// ======
var group1 = dialog.add("group", undefined, {name: "group1"}); 
    group1.orientation = "column"; 
    group1.alignChildren = ["fill","center"]; 
    group1.spacing = 10; 
    group1.margins = 0; 

var ok = group1.add("button", undefined, undefined, {name: "ok"}); 
    ok.text = "Ok"; 

var cancel = group1.add("button", undefined, undefined, {name: "cancel"}); 
    cancel.text = "Cancel"; 

// Item Reference List (variable names):
/*
  textInput
  ok
  cancel
*/

// Item Reference List (findElement):
/*
  dialog.findElement('textInput');
  dialog.findElement('ok');
  dialog.findElement('cancel');
*/

// Item Reference List (item path):
/*
  dialog.panel1.textInput
  dialog.group1.ok
  dialog.group1.cancel
*/

dialog.show();
```

### By the way, the difference between these 3 formats is this:

- **Variable name:** — Shortest but you can only access this in the same scope.
- **Item Path:** - This you can use as long as you have access to the dialog object. This can easily get pretty long if you have nested items. 
- **FindElement method:** - This you can also use if you have access to the dialog object. This has the potential to be way shorter than `Item Path` if you have those pesky nested items and perhaps more importantly way simpler. Not to mention since this doesn't care about the object structure, you can keep using `findElement` even if you move this item anywhere within the dialog. Although as far as SDB is concerned, it needs to have a custom name or the automatically assigned name may change and cause it to break.

An example using the sample panel:

```Javascript
// Variable Name
statictext11.text
// Item Path
dialog.group4.panel3.group6.statictext11.text
// FindElement method
dialog.findElement("statictext11").text
```

______

### Here comes the "me nitpicking your code example extravaganza":

You return every single item you need outside of the function. This isn't a bad practice and can work just fine... I've done it like a kazillion times. That said, it's unnecessary in this case. Every item that has the `creation property` = `name` can be fished out from the dialog object.

Without really changing any of the structure there, I would get rid of that and simply return the dialog object:

> A fairly compact example

```Javascript
function getDialog() {
	var dialog = new Window("dialog"); 
	
	var group1 = dialog.add("group", undefined, {name: "group1"});
	    group1.spacing = 10; 
	
	var ok = group1.add("button", undefined, undefined, {name: "ok"}); 
	    ok.text = "Ok"; 
	
	var cancel = group1.add("button", undefined, undefined, {name: "cancel"}); 
	    cancel.text = "Cancel"; 

	return dialog;
}


function init() {

    var dialog = getDialog();
	// Dialog customization
	dialog.margin = 20;
	dialog.group1.ok.text = 'Not really ok...';
	// or especially if the item is nested deep down, 
	// you could also use the `findElement` method:
	dialog.findElement('cancel').text = 'Abort Abort!!';
	// or store it as a variable:
	var cancelBtn = dialog.findElement('cancel');
	cancelBtn.text = 'Ahhh.. Nevermind..';
	dialog.show();
	
	// Other things...
}

init();
```

**Comment by AlexMuc2** [comment]
Hi Joonas,
thank you for your patience. Your compact example ist very good and more structured because the building of the dialog is separated from the init part. 
Working that way I think (for me), it's OK to keep the simplest way and only add the item reference list. With that, everyone can do what he / she want's / needed. 
Because I'm new to this, I don't know enough to decide, whats the best to implement. 

For me, I will try to start this java part from Applescript (witch is my main playground) with do javascript. In Applescript this will possible look like "set myASResult to do javascript myFileReference". Hopefully I will find a way to pass some Parameters this way to the javascript. 
The main reason why I found your site was, that I Wass looking for a simpler way to build Dialogs for Indesign. Mostly all (of May work)  could done with pure Applescript but if I need handlers to dynamically change items in an modal dialog than Applescript is coming to it's borders. The event listeners are not usable for dialogs (at leastI didm't find any sample. Everyone is telling: use ScriptUP instead...). So here I am :-)

**Comment by joonaspaakko** [comment]
It sounded like you haven't yet looked into or figured out how to go from `AppleScript` to `Javascript` to `AppleScript`, so I made you an example.

### Here's the example:

The AppleScript code triggers the specified Javascript file in Indesign with 2 parameters: `OK (appleScript)` and `Cancel (applescript)`. Then in the Javascript file I change the SUI button names to match the two parameters and in the end return the string `'JimmyJohn'` back to the AppleScript.

Of course you could make this way more complex by converting strings to JSON, for example.

> Additionally, there's a pretty good example about `do script` in the [Indesign Scripting Guide](https://www.adobe.com/content/dam/acom/en/devnet/indesign/sdk/cs6/scripting/InDesign_ScriptingGuide_AS.pdf).


AppleScript:
```Applescript
tell application "Adobe InDesign CC 2018"
	set myParameters to {"OK (appleScript)", "Cancel (applescript)"}
	set myJavascript to POSIX file "/Users/joonaspaakko/Library/Preferences/Adobe InDesign/Version 13.0/en_US/Scripts/Scripts Panel/myJavascript.jsx"
	set SUI to do script myJavascript language javascript with arguments myParameters
	do shell script "echo " & SUI -- Shows the returned string in the Script Editor.App
end tell
```

Javascript:
```Javascript

init( arguments ); // AppleScript parameters are passed over using an array called "arguments"

function init( applescript ) { // Here I just decided I wanted to call the array something different, as it enters the init function...

  var dialog = getDialog();
  dialog.findElement('ok').text = applescript[0];
  dialog.findElement('cancel').text = applescript[1];
  dialog.show();
	
  // Other things...

  return 'JimmyJohn'; // This is returned back to AppleScript
}



function getDialog() {
  var dialog = new Window("dialog"); 
	
  var group1 = dialog.add("group", undefined, {name: "group1"});
      group1.spacing = 10; 
	
  var ok = group1.add("button", undefined, undefined, {name: "ok"}); 
      ok.text = "Ok"; 
	
  var cancel = group1.add("button", undefined, undefined, {name: "cancel"}); 
      cancel.text = "Cancel"; 

  return dialog;
}

```

**Comment by AlexMuc2** [comment]
Oh, thanks, again. 
Yes, i didn't look because I first wan't to out, what is possible with javascript. Now you did my job presenting everything on a silver plate :-) Even the Parameter parsing from AS to JS.
Soon after writing this, I will put your samples to my toolbox for further use. How have people have figured out this without internet earlier? Many many thanks for your nice advice.

Michael

**Comment by joonaspaakko** [comment]
No problem. I know I wouldn't have figured out coding without the internet for sure...

**Comment by joonaspaakko** [comment]
It's now been added:

![2019-09-15 22 00 09](https://user-images.githubusercontent.com/1164476/64926279-68ba0100-d804-11e9-8d3d-06794e6f9351.gif)

**Comment by joonaspaakko** [comment]
I decided it was best to wrap this in an object. It does make it a bit beefier but this way it's safer to leave it in place.

It also adds yet another way to access the items from the `dialog` object  (see the bottom of the code):
```Javascript
var dialog = (function () {

  /*
  Code for Import https://scriptui.joonas.me — (Triple click to select): 
  {"activeId":2,"items":{"item-0":{"id":0,"type":"Dialog","parentId":false,"style":{"enabled":true,"varName":null,"windowType":"Dialog","creationProps":{"su1PanelCoordinates":false,"maximizeButton":false,"minimizeButton":false,"independent":false,"closeButton":true,"borderless":false,"resizeable":false},"text":"Dialog","preferredSize":[0,0],"margins":16,"orientation":"column","spacing":10,"alignChildren":["center","top"]}},"item-1":{"id":1,"type":"Button","parentId":0,"style":{"enabled":true,"varName":"saveButton","text":"Save","justify":"center","preferredSize":[0,0],"alignment":null,"helpTip":null}},"item-2":{"id":2,"type":"StaticText","parentId":0,"style":{"enabled":true,"varName":"textItem","creationProps":{"truncate":"none","multiline":false,"scrolling":false},"softWrap":false,"text":"StaticText","justify":"left","preferredSize":[0,0],"alignment":null,"helpTip":null}}},"order":[0,1,2],"settings":{"importJSON":true,"indentSize":false,"cepExport":false,"includeCSSJS":true,"showDialog":false,"functionWrapper":true,"afterEffectsDockable":false,"itemReferenceList":"find"}}
  */ 

  // DIALOG
  // ======
  var dialog = new Window("dialog"); 
      dialog.text = "Dialog"; 
      dialog.orientation = "column"; 
      dialog.alignChildren = ["center","top"]; 
      dialog.spacing = 10; 
      dialog.margins = 16; 

  var saveButton = dialog.add("button", undefined, undefined, {name: "saveButton"}); 
      saveButton.text = "Save"; 

  var textItem = dialog.add("statictext", undefined, undefined, {name: "textItem"}); 
      textItem.text = "StaticText"; 

  // ITEM REFERENCE LIST ( Info: http://jongware.mit.edu/Sui/index_1.html ) 
  dialog.items = { 
    saveButton: dialog.findElement("saveButton"), // button
    textItem: dialog.findElement("textItem") // statictext
  };
  dialog.items.array = [saveButton, textItem];

  return dialog;

}());

dialog.items.saveButton.text = 'Export';
dialog.show();
```
