### ISSUE TITLE
Does not work in Firefox

### ISSUE THREAD

**Issue by grefel** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#67]
Would be great if this web app could work with Firefox.

**Comment by joonaspaakko** [comment]
True. 

If I’d made this years ago, I probably would’ve supported at least Chrome and Firefox. The original idea was all modern browsers actually... It’s just too much work at this point and I'm not ready to even consider it right now. I won't completely dismiss the idea, but it seems like tons of work...

The pseudo [desktop apps](https://www.dropbox.com/sh/4wy71qv8e08deh1/AADJYT4BJRQQuJvVjl5CaYgUa?dl=0) may help a tiny bit with this. Of course if you already have Chrome installed, they don't really make things any more convenient.

**Comment by thebodzio** [comment]
Are you deliberately using some Chrome specific functionality? I just opened your editor in FF (removing the modal window) and it seems to work fine beside snapshots. Perhaps a warning instead of a permanent blockade would be better suited here? Simply: "FF is not supported. You are using this software on your own responsibility. Complaints and FF related bugs will be kindly ignored 😉 ".

How about that? 😃

**Comment by joonaspaakko** [comment]
@thebodzio, yea, no browser specific features, at least where it really matters. Many of the bugs I've seen in other browsers are visual or partially working and that makes them hard to detect. I don't want to spend all that time looking for these bugs in other browsers... I did it for a while but they just kept popping up. I figured that keeping it restricted to one browser is not a terrible compromise since it reduces my stress and gives everyone a consistent experience.

> This was actually a relatively recent change. There was an [issue that brought it up](https://github.com/joonaspaakko/ScriptUI-Dialog-Builder-Joonas/issues/64) again, which lead me to finally block all other browsers. My suggestion link(s) in the issue are likely all gone now. I did briefly consider having a link that would let users close the overlay, but I decided against it in favor of consistent user experience.

**Comment by thebodzio** [comment]
@joonaspaakko That's exactly the reason I thought about and it makes sense, but I still think that some warning with a short explanation that user will be able to close/hide is altogether a better solution. I mean: it's easy enough as it is (at least in FF), it's just not very convenient 😄. I hope you will reconsider, especially since it may (a slim chance as it is 😉) prevent raising issues like the very one we're discussing now.

**Comment by joonaspaakko** [comment]
I don't think that will happen. As long as no one is fixing bugs in other browsers, it just doesn't make sense to allow people to use them. Maybe there will be time to tackle the issues in other browsers later, but for now I don't see myself doing that.

I wouldn't recommend closing the overlay manually either.

**Comment by thebodzio** [comment]
I can sympathize and understand why you want to stick to developing for and supporting one browser. That makes perfect sense. Disallowing people to use other browsers, however, does not. But, hey, it's your show 😄 and, to be sure, it's a darn good one, despite the latter fact.

> I wouldn't recommend closing the overlay manually either.

Yeaaa... I know... but I will, anyway... 😃. I just love the sound of my warranty going void 😉. Especially when everything that I care about works fine even with the sticker removed 😉.

Cheers! All the best! 😃
