### ISSUE TITLE
It works fine on Firefox, so disable the stupid browser police thing.

### ISSUE THREAD

**Issue by stibinator** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#77]
If you block all the modal browser police shite, this website works fine on Firefox. Please stop forcing your users to use a browser that spies on them.

Steps to reproduce:
Open the website on firefox.
Use the developer tools to hide the modal overlays, and delete the "modal active" class from the main div.
Use the website as normal, 100% functional

Expected: possible problems using the website because chrome has some magic function that non-spyware browsers don't have
Observed: works perfectly, except for the stupid browser police nag screen. See example, created on firefox.
[uitest.txt](https://github.com/joonaspaakko/ScriptUI-Dialog-Builder-Joonas/files/4398147/uitest.txt)

**Comment by joonaspaakko** [comment]
SDB was developed in Chrome and so it's been thousands of times in that platform. I was fixing bugs in other browsers for a while, but I eventually gave up and decided to prioritize consistent UX and output by adding the blockage. It could work in other browsers just as well, if I spent a whole lot of time fixing things, which I don't see myself doing given the shelf life of this thing at this point. Just because you can't see them, don't mean the issues aren't there. Also Firefox is not the only other browser out there. I just don't see myself maintaining it for multiple browsers. Sorry.

I suggest you try the pseudo desktop apps mentioned in the [readme](https://github.com/joonaspaakko/ScriptUI-Dialog-Builder-Joonas#desktop-applications--chrome-app). They run on Chromium, just like many other desktop applications, like for instance Visual Studio Code. The only difference is that these apps load up SBD's website, which is why I call them pseudo desktop apps.

**Comment by joonaspaakko** [comment]
(Linking for reference) #67
