### ISSUE TITLE
Request: Loading Progress Bar

### ISSUE THREAD

**Issue by StormCtrl** [joonaspaakko/ScriptUI-Dialog-Builder-Joonas#83]
Hey Joonas!

I would like to request to add the Progress Bar as an option to the interface:

Snippet of a code:
var pb = groupOne.add("progressbar", undefined, "ProgressBar");
			pb.value = 50;

**Comment by joonaspaakko** [comment]
I don't see why not, but I'm not making any promises.

**Comment by joonaspaakko** [comment]
@StormCtrl, I'm planning to give it the same treatment as the item `Slider`, with no value adjustment in SDB. 

> It wouldn't be a Herculean task to add a `value` input, but it seems a little pointless from a visual standpoint. 

**Any objections?**

I think it would make sense to show 50% progress in the dialog preview to make it very clear what it is, and not just a faint outline of a thing, but would it make sense to export it (`without a value` or `progress.value = 0;`)  instead of `progress.value = 50;`? There would be a bit of a disconnect between what you see and what you get, but I feel like you'd most of the time start from 0 anyways, so it would make sense? Either way, I don't think it's a big deal, just thinking out loud.

It would still have general properties, you just can't change the progress `value` in SDB:
![image](https://user-images.githubusercontent.com/1164476/85853111-9fbd3a00-b7ba-11ea-8326-f8f9d3ac61df.png)

**Comment by StormCtrl** [comment]
Perfectly fine! Thx for implementing it!

**Comment by joonaspaakko** [comment]
@StormCtrl, it's now been added. I decided to keep the value 50 on export so it won't be confusing. 

![Screen Shot 2020-07-05 at 11 47 30 PM](https://user-images.githubusercontent.com/1164476/86541943-eaa52300-bf19-11ea-9612-ea2c3c1f2953.png)
